install.packages("tidyverse", repos = "http://cran.us.r-project.org")
install.packages("rmarkdown", repos = "http://cran.us.r-project.org")
install.packages("httr", repos = "http://cran.us.r-project.org")
install.packages("shinydashboard", repos = "http://cran.us.r-project.org")
install.packages("leaflet", repos = "http://cran.us.r-project.org")
install.packages("methods", repos = "http://cran.us.r-project.org")
install.packages("jpeg", repos = "http://cran.us.r-project.org")
